[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test/foundry"

# Solidity compiler settings
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200

# Test settings
verbosity = 2
gas_reports = ["*"]

# Fork settings for testing
[rpc_endpoints]
sepolia = "${FORK_URL}"

# Environment variables
[profile.default.env]
WORLD_ID_ROUTER_ADDRESS = "${WORLD_ID_ROUTER_ADDRESS}"
WORLD_ID_APP_ID = "${WORLD_ID_APP_ID}"
WORLD_ID_ACTION = "${WORLD_ID_ACTION}"
